### ISSUE TITLE
Apache Certification Expired and prevent IPA service to start.

### ISSUE THREAD

**Issue by malizadeh** [smartbit/labipa-rhcsa-rhce#1]

**Comment by smartbit** [comment]
```
certutil -L -d /etc/httpd/alias -n Server-Cert | grep Vali -A2
        Validity:
            Not Before: Sun Apr 17 09:45:07 2016
            Not After : Wed Apr 18 09:45:07 2018
```
Its seems the IPA cert has expired on April 18, 2018. Please contact Sander. He might create new images.

**Comment by malizadeh** [comment]
Thanks, 
Sander created new labipa server and everyone can download it from here : https://www.rhatcert.com/pub/labipa-3.2-1.zip
